/**
 * Internal error codes for API responses.
 * Frontend can use these codes to translate error messages to user's language.
 *
 * Naming convention: CATEGORY_SPECIFIC_ERROR
 * Categories:
 * - AUTH: Authentication/Authorization errors
 * - VALIDATION: Input validation errors
 * - RESOURCE: Resource not found or access errors
 * - PAYMENT: Payment/Stripe related errors
 * - TASK: Task creation/processing errors
 * - USER: User-related errors
 * - SERVER: Internal server errors
 */

const ErrorCodes = {
    // Authentication & Authorization
    AUTH_NOT_AUTHORIZED: "AUTH_NOT_AUTHORIZED",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_OUTDATED_TOKEN: "AUTH_OUTDATED_TOKEN",
    AUTH_EMAIL_OR_PASSWORD_WRONG: "AUTH_EMAIL_OR_PASSWORD_WRONG",
    AUTH_EMAIL_IN_USE: "AUTH_EMAIL_IN_USE",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_TOKEN_USED: "AUTH_TOKEN_USED",
    AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
    AUTH_EMAIL_ALREADY_VERIFIED: "AUTH_EMAIL_ALREADY_VERIFIED",

    // Validation errors
    VALIDATION_FAILED: "VALIDATION_FAILED",
    VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
    VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
    VALIDATION_INVALID_YEAR: "VALIDATION_INVALID_YEAR",
    VALIDATION_YEAR_OUT_OF_RANGE: "VALIDATION_YEAR_OUT_OF_RANGE",
    VALIDATION_INVALID_AMOUNT: "VALIDATION_INVALID_AMOUNT",

    // Resource errors
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_BRAND_NOT_FOUND: "RESOURCE_BRAND_NOT_FOUND",
    RESOURCE_MODEL_NOT_FOUND: "RESOURCE_MODEL_NOT_FOUND",
    RESOURCE_TASK_NOT_FOUND: "RESOURCE_TASK_NOT_FOUND",
    RESOURCE_REPORT_NOT_FOUND: "RESOURCE_REPORT_NOT_FOUND",
    RESOURCE_USER_NOT_FOUND: "RESOURCE_USER_NOT_FOUND",
    RESOURCE_IMAGE_NOT_FOUND: "RESOURCE_IMAGE_NOT_FOUND",
    RESOURCE_SESSION_NOT_FOUND: "RESOURCE_SESSION_NOT_FOUND",
    RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",

    // Task errors
    TASK_CREATION_FAILED: "TASK_CREATION_FAILED",
    TASK_PROCESSING_FAILED: "TASK_PROCESSING_FAILED",
    TASK_IMAGES_REQUIRED: "TASK_IMAGES_REQUIRED",
    TASK_ALREADY_PAID: "TASK_ALREADY_PAID",
    TASK_NOT_PAID: "TASK_NOT_PAID",
    TASK_ANALYSIS_FAILED: "TASK_ANALYSIS_FAILED",

    // Payment errors
    PAYMENT_STRIPE_NOT_CONFIGURED: "PAYMENT_STRIPE_NOT_CONFIGURED",
    PAYMENT_WEBHOOK_FAILED: "PAYMENT_WEBHOOK_FAILED",
    PAYMENT_SESSION_CREATION_FAILED: "PAYMENT_SESSION_CREATION_FAILED",
    PAYMENT_INVALID_CURRENCY: "PAYMENT_INVALID_CURRENCY",

    // User errors
    USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
    USER_AVATAR_UPLOAD_FAILED: "USER_AVATAR_UPLOAD_FAILED",

    // Email errors
    EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
    EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",

    // Rate limiting errors
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    RATE_LIMIT_PASSWORD_RESET: "RATE_LIMIT_PASSWORD_RESET",
    RATE_LIMIT_TASK_RETRY: "RATE_LIMIT_TASK_RETRY",
    RATE_LIMIT_EMAIL_VERIFICATION: "RATE_LIMIT_EMAIL_VERIFICATION",

    // Server errors
    SERVER_ERROR: "SERVER_ERROR",
    SERVER_DATABASE_ERROR: "SERVER_DATABASE_ERROR",
    SERVER_EXTERNAL_API_ERROR: "SERVER_EXTERNAL_API_ERROR",
};

export default ErrorCodes;
